version: '3.8'

services:
  web:
    image: php:8.1-apache
    container_name: humhub-web
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./docker/apache/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db
    working_dir: /var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    command: bash -c "
      apt-get update && apt-get install -y \
        libpng-dev libjpeg-dev libonig-dev libxml2-dev zip unzip \
        libzip-dev libicu-dev g++ git curl mariadb-client \
        libexif-dev libldap2-dev nodejs npm && \
      npm install -g grunt-cli && \
      cd /var/www/html && \
      npm install && \
      docker-php-ext-configure gd --with-jpeg && \
      docker-php-ext-install pdo pdo_mysql gd intl zip exif ldap && \
      apache2-foreground"

  db:
    image: mariadb:10.5
    container_name: humhub-db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: humhub
      MYSQL_USER: humhub
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

  # Docker common commands
  # ---------------------
  # docker compose up --build // Build/start
  # docker compose down // Stop
  # docker-compose restart web // Restart
  # docker exec -it humhub-web bash // Access container
  # php protected/yii asset protected/humhub/config/assets.php protected/humhub/config/assets-prod.php // Generate assets
  # mysql -h db -u humhub -p // MySQL connect from container